server:
  port: 8980
spring:
  profiles:
    active: dev
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          #配置Git仓库地址
          uri: https://github.com/gywgiehub/gyw.github.io.git
          #配置文件在仓库中位置
          search-paths: spring-cloud-config-repo
          #Git仓库的账号
          username: gywgiehub
          #Git仓库的密码
          password: q78361900
          #仓库分支
          default-label: master
  #mysql数据库链接
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: mysql://127.0.0.1:3306/tf_${spring.application.name}?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
      username: root
      password: colorful
eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址
      defaultZone: http://localhost:8761/eureka/
