server:
  port: 8761
eureka:
  client:
    #是否将自己注册到Eureka Server
    register-with-eureka: false
    #是否从Eureka Server获取注册信息这是一个单点的Eureka Server不需要同步其他Eureka Server因此设置false
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址，默认就为http://localhost:8761/eureka多个地址可使用逗号分隔
      defaultZone: http://localhost:8761/eureka